/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnotationsRouteImport } from './routes/annotations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationsRoute = AnnotationsRouteImport.update({
  id: '/annotations',
  path: '/annotations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRoute
  '/auth': typeof AuthRoute
  '/engine': typeof EngineRoute
  '/evidence': typeof EvidenceRoute
  '/evolution': typeof EvolutionRoute
  '/explorer': typeof ExplorerRoute
  '/financials': typeof FinancialsRoute
  '/industry': typeof IndustryRoute
  '/market': typeof MarketRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/scanner': typeof ScannerRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRoute
  '/auth': typeof AuthRoute
  '/engine': typeof EngineRoute
  '/evidence': typeof EvidenceRoute
  '/evolution': typeof EvolutionRoute
  '/explorer': typeof ExplorerRoute
  '/financials': typeof FinancialsRoute
  '/industry': typeof IndustryRoute
  '/market': typeof MarketRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/scanner': typeof ScannerRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRoute
  '/auth': typeof AuthRoute
  '/engine': typeof EngineRoute
  '/evidence': typeof EvidenceRoute
  '/evolution': typeof EvolutionRoute
  '/explorer': typeof ExplorerRoute
  '/financials': typeof FinancialsRoute
  '/industry': typeof IndustryRoute
  '/market': typeof MarketRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/scanner': typeof ScannerRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annotations'
    | '/auth'
    | '/engine'
    | '/evidence'
    | '/evolution'
    | '/explorer'
    | '/financials'
    | '/industry'
    | '/market'
    | '/reports'
    | '/repository'
    | '/scanner'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annotations'
    | '/auth'
    | '/engine'
    | '/evidence'
    | '/evolution'
    | '/explorer'
    | '/financials'
    | '/industry'
    | '/market'
    | '/reports'
    | '/repository'
    | '/scanner'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/annotations'
    | '/auth'
    | '/engine'
    | '/evidence'
    | '/evolution'
    | '/explorer'
    | '/financials'
    | '/industry'
    | '/market'
    | '/reports'
    | '/repository'
    | '/scanner'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnotationsRoute: typeof AnnotationsRoute
  AuthRoute: typeof AuthRoute
  EngineRoute: typeof EngineRoute
  EvidenceRoute: typeof EvidenceRoute
  EvolutionRoute: typeof EvolutionRoute
  ExplorerRoute: typeof ExplorerRoute
  FinancialsRoute: typeof FinancialsRoute
  IndustryRoute: typeof IndustryRoute
  MarketRoute: typeof MarketRoute
  ReportsRoute: typeof ReportsRoute
  RepositoryRoute: typeof RepositoryRoute
  ScannerRoute: typeof ScannerRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotations': {
      id: '/annotations'
      path: '/annotations'
      fullPath: '/annotations'
      preLoaderRoute: typeof AnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnotationsRoute: AnnotationsRoute,
  AuthRoute: AuthRoute,
  EngineRoute: EngineRoute,
  EvidenceRoute: EvidenceRoute,
  EvolutionRoute: EvolutionRoute,
  ExplorerRoute: ExplorerRoute,
  FinancialsRoute: FinancialsRoute,
  IndustryRoute: IndustryRoute,
  MarketRoute: MarketRoute,
  ReportsRoute: ReportsRoute,
  RepositoryRoute: RepositoryRoute,
  ScannerRoute: ScannerRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
